// Generated by LiveScript 1.2.0
(function(){
  var linksRef;
  linksRef = new PgBase("http://localhost:3000/links");
  window.LINK2ITEM = function(link){
    return "<div class=\"item\">\n  <div class=\"right floated tiny teal\">" + moment(link.create_date).fromNow() + "</div>\n  <div class=\"content\">\n    <a class=\"header link-click\" data-id=\"" + link._id + "\">" + link.title + "</a>\n    <div class=\"description\">\n      <i class=\"red arrow up icon\"></i>\n      " + link.rating + "\n      " + link.url + "\n      </div>\n  </div>\n</div>";
  };
  window.GET_COMMENT = function(link_id, cb){
    var socketRef;
    socketRef = new PgBase("http://localhost:3000/comments");
    console.log(socketRef);
    socketRef.needConnection();
    return socketRef.socket.emit("GET:comments", {
      q: "{\"link_id\":" + link_id + "}"
    }, function(it){
      return cb(it);
    });
  };
  linksRef.once('value', function(it){
    var i$, ref$, len$, link;
    for (i$ = 0, len$ = (ref$ = it.reverse()).length; i$ < len$; ++i$) {
      link = ref$[i$];
      $('#link-list').append(LINK2ITEM(link));
    }
    return console.log('value', it);
  });
  linksRef.on('child_added', function(it){
    $('#link-list').prepend(LINK2ITEM(link));
    return console.log('added', it);
  });
  $(function(){
    $('#submit-button').on('click', function(){
      var link;
      link = {
        title: $('#submit-title').val(),
        url: $('#submit-link').val(),
        rating: 0
      };
      return linksRef.push(link);
    });
    $('body').on('keypress', '#comment-input', function(it){
      var commentRef, link_id, link_body, new_comment;
      if (it.keyCode === 13) {
        commentRef = new PgBase("http://localhost:3000/comments");
        link_id = $(it.target).data('link-id');
        link_body = $(it.target).val();
        new_comment = {
          link_id: link_id,
          body: link_body
        };
        $(it.target).val("");
        return commentRef.push(new_comment, function(){
          return $('#comment-sect').prepend("<div class=\"ui secondary segment\">\n  <p>" + link_body + "</p>\n</div>");
        });
      }
    });
    return $('body').on('click', '.link-click', function(it){
      var id, postRef;
      id = $(it.target).data("id");
      console.log(id);
      postRef = new PgBase("http://localhost:3000/links/" + id);
      return postRef.once('value', function(it){
        console.log(it);
        $('#main').html("<h2 class=\"ui header\">\n" + it.title + "\n<div class=\"sub header\"><i class=\"red arrow up icon\"></i>\n        " + it.rating + "\n        " + it.url + "\n            </div>\n    </h2>\n    <div class=\"ui input focus fluid icon\">\n      <input type=\"text\" placeholder=\"Leave comment...\" id=\"comment-input\" data-link-id=\"" + it._id + "\">\n      <i class=\"outline comment icon\"></i>\n    </div>\n  </div>\n</div>\n<div id=\"comment-sect\" style=\"padding-top: 20px\"></div>");
        return GET_COMMENT(id, function(it){
          var i$, ref$, len$, c, results$ = [];
          console.log(it);
          for (i$ = 0, len$ = (ref$ = it.entries).length; i$ < len$; ++i$) {
            c = ref$[i$];
            results$.push($('#comment-sect').append("<div class=\"ui secondary segment\">\n  </h3>\n  <p>" + c.body + "</p>\n</div>"));
          }
          return results$;
        });
      });
    });
  });
}).call(this);
